users:
  -
    name: nomal
    email: normal_user@gmail.com
    password: "123456"
    password_confirmation: "123456"
    role: 0
    activated: true
  - 
    name: admin
    email: admin@gmail.com
    password: "123456"
    password_confirmation: "123456"
    role: 1
    activated: true
    
authors:
  -
    name: J.K.Rowling

categories:
  -
    name: fiction
  -  
    name: horror
  -
    name: adventure
    
books:
  -
    title: Harry Potter And The Chamber of Secrets
    publisher: Arthur A. Levine Books
    cover_image: <%= Rails.root.join("app/assets/images/book/book1.jpeg") %>
    describe: "Harry Potter and the Chamber of Secrets is a fantasy novel written 
    by British author J. K. Rowling and the second novel in the Harry Potter series. 
    The plot follows Harry's second year at Hogwarts School of Witchcraft and Wizardry,
    during which a series of messages on the walls of the school's corridors 
    warn that the Chamber of Secrets has been opened and that the heir of Slytherin
    would kill all pupils who do not come from all-magical families. 
    These threats are found after attacks which leave residents of the school petrified (frozen like stone).
    Throughout the year, Harry and his friends Ron and Hermione investigate the attacks."